# Base Image
FROM python:3.14-slim

# Copy prebuilt uv binary
COPY --from=ghcr.io/astral-sh/uv:0.11.8 /uv /uvx /bin/

# Set working directory
WORKDIR /bills_st

# Copy dependency files first (for layer caching)
COPY pyproject.toml uv.lock ./

# Install dependencies
RUN uv sync --locked

# Copy the rest of the app
COPY . .

# Expose Streamlit port
EXPOSE 8501

# Run the app
CMD ["uv",\
     "run",\
     "streamlit",\
     "run",\
     "app.py",\
     "--server.port=8501",\
     "--server.address=0.0.0.0"]
